export { default as Book } from './book'
export { default as Music } from './music'
export { default as Pencil } from './pencil'
export { default as Reading } from './reading'
export { default as Play } from './play'
export { default as Document } from './document'

export { default as GitHub } from './github'
export { default as Twitter } from './twitter'
export { default as Mail } from './mail'
export { default as Quote } from './quote'
